{
 "title": "Channel Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mirthInstance",
    "label": "Instance",
    "query": {
     "query": "label_values(mirth_server_state,exported_instance)"
    }
   },
   {
    "name": "channelName",
    "label": "Channel",
    "query": {
     "query": "label_values(mirth_messages_received_total{exported_instance=\"$mirthInstance\"},channelName)"
    }
   },
   {
    "name": "interval",
    "query": "2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "${mirthInstance}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "mirthInstance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(mirth_messages_received_total{channelName=\"$channelName\", exported_instance=~\"$mirthInstance\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$mirthInstance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "mirthInstance" },
  {
   "title": "Total Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (exported_instance, channelName) (mirth_messages_received_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"} - mirth_messages_received_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"} offset $__interval) > 0\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (exported_instance, channelName) (mirth_messages_sent_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"} - mirth_messages_sent_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"} offset $__interval) > 0\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Filtered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (exported_instance, channelName) (mirth_messages_filtered_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"} - mirth_messages_filtered_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"} offset $__interval) > 0\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errored",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (exported_instance, channelName) (mirth_messages_errored_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"} - mirth_messages_errored_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"} offset $__interval) > 0\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Queued",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(exported_instance, channelName) (mirth_messages_queued{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Message Stats (Over Time)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Received by Hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (time) (mirth_messages_received_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} - mirth_messages_received_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} offset $__interval)",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "Received Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "mirth_messages_received_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} - mirth_messages_received_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} offset $__interval",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Total Sent by Hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (time) (mirth_messages_sent_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} - mirth_messages_sent_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} offset $__interval)",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "Sent Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "mirth_messages_sent_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} - mirth_messages_sent_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} offset $__interval",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Total Errored by Hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (time) (mirth_messages_errored_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} - mirth_messages_errored_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} offset $__interval)",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "Errored Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "mirth_messages_errored_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} - mirth_messages_errored_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} offset $__interval",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Total Filtered by Hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (time) (mirth_messages_filtered_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} - mirth_messages_filtered_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} offset $__interval)",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "Filtered Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 35 },
   "targets": [
    {
     "expr": "mirth_messages_filtered_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} - mirth_messages_filtered_total{exported_instance=~\"$mirthInstance\", channelName=\"$channelName\"} offset $__interval",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}